apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  ClusterIp: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017