apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      command: ["/bin/sh"]
      args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
      containers:
      - name: mongodb
        image: mongo
        resources:
          requests:
            memory: 1000Mi
            cpu: 200m
          limits:
            memory: 1500Mi
            cpu: 200m
        ports:
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
             name: mongodb-secret
             key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mongodb-secret
             key: mongo-root-password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumeClaimTemplates:
      - metadata:
          name: mongo-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi