apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: mongodb
spec:
  serviceName: mongodb
  replicas: $mongodb_replica_count
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
      containers:
      - name: mongodb
        image: mongo
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
             name: mongodb-secret
             key: MONGO-ROOT-USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mongodb-secret
             key: MONGO-ROOT-PASSWORD
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db