controller:
  service:
    externalIPs: [192.168.1.200]
  config:
    server-snippet: |
      location ~* "^/(.*)" {
          if ($request_method =  "POST") {
            return 403;
          } 
      }
    use-forwarded-headers: true
    use-gzip: true
    generate-request-id: true
    proxy-body-size: 1024k
    client-body-buffer-size: 1024k
    client-header-buffer-size: 1024k
    error-log-level: warn
    http2-max-header-size: 1024k
    log-format-escape-json: true
    log-format-upstream: '{"time": "", "remote_addr": "", "x_forwarded_for": "", "request_id": "","remote_user": "", "bytes_sent": , "request_time": , "status": , "vhost": "", "request_proto": "",   "path": "", "request_query": "", "request_length": , "duration": ,"method": "", "http_referrer": "","http_user_agent": "" }'
  # replicaCount: 2
