apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  NODE_ENV: develop
  TESTNET_BASE_URL: https://testnet.binance.vision/
  TESTNET_WS_BASE_URL: wss://testnet.binance.vision:9443
  BINANCE_BASE_URL: https://api.binance.com
  BINANCE_WS_BASE_URL: wss://stream.binance.com:9443
  ACCESS_TOKEN_SECRET: jwttestaccess
  REFRESH_TOKEN_SECRET: jwttestrefresh
  ACCESS_TOKEN_LIFETIME: '50'
  REFRESH_TOKEN_LIFETIME: '50'
  SERVER_PORT: '3000'
  MONGODB_URI: mongodb-service
  SERVER_URI: server-service
  provaaaaaaa: ${prova}